server:
  port: 8092
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shixiutingfen/configserver.git
          username: shixiutingfen
          password: manjie410
  application:
        name: configservermodule

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
