spring:
    elasticsearch:
      jest:
       uris:
       - http://192.168.0.130:9200
       read-timeout: 5000
    application:
      name: elasticsearchmodule

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
server:
  port: 8086